"""empty message

Revision ID: 251e8097f4ac
Revises: 413cbae9bbc0
Create Date: 2021-03-07 05:08:07.278366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '251e8097f4ac'
down_revision = '413cbae9bbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.drop_column('Movies', 'realease_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('realease_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Movies', 'release_date')
    # ### end Alembic commands ###
